MODEL:
  NAME: SAM3-Teacher
  BACKBONE: vit_h
  RESUME: sam3_checkpoints/sam3.pt

TRAIN:
  EPOCHS: 1

DATA:
  IMG_SIZE: 1008
  DATASET: sa1b
  DATA_PATH: data/sa-1b


DISTILL:
  EMBED_DIM: 1024
  EMBED_SIZE: 72
  SAVE_TEACHER_EMBED: True
  TEACHER_EMBED_PATH: output/stage1_teacher/embeddings/